-- ============================================================
-- pipeline_run_log — Audit and Gemini AI monitoring table
-- Grain: one row per pipeline run
-- No partitioning: low-volume audit table; full scans are fast.
-- Stores operational metadata and Gemini-generated summaries
--   for each Cloud Function / Dataform execution.
-- Project: flights-analytics-prod | Dataset: flights_dw
-- Region:  europe-west2
-- ============================================================

CREATE OR REPLACE TABLE `flights-analytics-prod.flights_dw.pipeline_run_log`
(
  run_id             STRING     NOT NULL,  -- PK: UUID generated by caller
  run_date           DATE       NOT NULL,
  run_timestamp      TIMESTAMP  NOT NULL,
  source             STRING     NOT NULL,  -- e.g. 'ingest_bts_csv', 'ingest_fr24'
  total_rows_loaded  INT64,
  rows_rejected      INT64,
  avg_delay_minutes  FLOAT64,
  gemini_summary     STRING,               -- Gemini-generated plain-English run summary
  pipeline_status    STRING     NOT NULL,  -- 'SUCCESS' | 'PARTIAL' | 'FAILED'
  created_at         TIMESTAMP  NOT NULL
)
OPTIONS (
  description = 'Pipeline audit and Gemini AI monitoring log. One row per pipeline run. Stores row counts, quality metrics, and Gemini-generated summaries.'
);
