name: "PR Quality Checks"

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'cloud_functions/**'
      - 'spark_jobs/**'
      - 'dbt/**'

jobs:
  lint-and-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Linting Tools
        run: |
          pip install ruff bandit

      - name: Run Ruff (Linting)
        # This will catch the 'typing.Dict' vs 'dict' issues
        run: ruff check .

      - name: Run Bandit (Security)
        # This checks for hardcoded keys or unsafe library usage
        run: bandit -r . -x ./tests